#jwt:
#  secret: oiasjfoiasj8asd23124!####9u203i49jioh!$$
#  expirationInMinutes: 1500
#  issuer: tvz

spring:
  application:
    name: news-portal
  jpa:
    show-sql: true
    open-in-view: false
    generate-ddl: false
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/news-portal
    username: edi
    password: 'edi'
server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/